swagger: '2.0'
info:
  description: |
    This is a documentation for RepairOrder services
  version: "1.0.1"
  title: Swagger RepairOrder
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# basePath: /repair
# schemes:
# - http
paths:
  /order:
    post:
      tags:
      - pet
      summary: Add a new repairOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: repairOrder object that needs to be created for the repairer
        required: true
        schema:
          $ref: '#/definitions/RepairOrder'
      responses:
        200: 
          description: Successfully complete
          schema:
            $ref: '#/definitions/RepairOrder'
        400: 
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
    
  
  /order/{orderId}:
    get:
      summary: Find repair order by orderId
      description: Returns a single repair order
      produces:
      - application/json
      
      parameters:
      - name: orderId
        in: path
        description: ID of repairOrder to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/RepairOrder'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        404:
          description: order id not found 
          schema:
            $ref: '#/definitions/Error'
 
    patch:
      
      summary: Cancel repairOrder by orderId
      description: Returns a single repair order that is cancelled
      produces:
      - application/json
      
      parameters:
      - name: orderId
        in: path
        description: ID of repairOrder to cancel
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/RepairOrder'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        404:
          description: order id not found 
          schema:
            $ref: '#/definitions/Error'
          
  /orders:
    get:
      
      summary: Get all repair orders
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/RepairOrder'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
  

definitions:
  RepairOrder:
    type: object
    required:
    - repairerName
    - startDateTime
    - duration
    properties:
      id:
        type: integer
        format: int64
      startDateTime:
        type: string
        format: date-time
        example: provide date time in format yyyy-mm-dd hh:mm:ss
      duration:
        type: string
        example: provide duration in format hh:mm:ss  
      orderStatusDescription:
        type: string
        enum:
          - Order has been placed but not yet delivered
          - Order is being delivered right now
          - Order has been delivered
          - Order was cancelled before delivery
          
  Error:
    type: object
    
    properties:
      status:
        type: integer
        format: int32
      errors:
        type: array
        items:
          type: string
               
      
  
  

host: virtserver.swaggerhub.com
basePath: /RachanaSaneSwagger/farmRepairOrder/1.0.0
schemes:
 - https
 - http